import { Navigate, createBrowserRouter } from 'react-router-dom'

import { AppShell } from './AppShell'
import {
  ActivityRoute,
  AuditRoute,
  AuditDetailsRoute,
  DevicesRoute,
  EndpointDetailsRoute,
  EventsRoute,
  EventDetailsRoute,
  IngestRoute,
  IngestDiagnosticDetailsRoute,
  IpDetailsRoute,
  OverviewRoute,
  ReviewDetailsRoute,
  RulesRoute,
  ShadowRunsRoute,
  ShadowRunDetailsRoute,
	CasesRoute,
	CaseDetailsRoute,
	OrganizationRoute,
	ActionsRoute,
	SecuritySettingsRoute,
} from './routePages'

export const router = createBrowserRouter([
  {
    path: '/',
    element: <AppShell />,
    children: [
      { index: true, element: <Navigate replace to="/overview" /> },
      { path: 'overview', element: <OverviewRoute /> },
      { path: 'activity', element: <ActivityRoute /> },
      { path: 'devices', element: <DevicesRoute /> },
      { path: 'devices/:endpointId', element: <EndpointDetailsRoute /> },
      { path: 'events', element: <EventsRoute /> },
      { path: 'events/:eventId', element: <EventDetailsRoute /> },
      { path: 'ingest', element: <IngestRoute /> },
      { path: 'ingest/diagnostics/:diagnosticId', element: <IngestDiagnosticDetailsRoute /> },
      { path: 'risks', element: <Navigate replace to="/cases" /> },
      { path: 'ips/:ip', element: <IpDetailsRoute /> },
      { path: 'review', element: <Navigate replace to="/cases" /> },
      { path: 'review/:caseId', element: <ReviewDetailsRoute /> },
	  { path: 'cases', element: <CasesRoute /> },
	  { path: 'cases/:caseId', element: <CaseDetailsRoute /> },
      { path: 'shadow-runs', element: <ShadowRunsRoute /> },
      { path: 'shadow-runs/:runId', element: <ShadowRunDetailsRoute /> },
      { path: 'audit', element: <AuditRoute /> },
      { path: 'audit/:auditId', element: <AuditDetailsRoute /> },
      { path: 'settings/rules', element: <RulesRoute /> },
	  { path: 'settings/organization', element: <OrganizationRoute /> },
	  { path: 'settings/actions', element: <ActionsRoute /> },
	  { path: 'settings/security', element: <SecuritySettingsRoute /> },
    ],
  },
])
