import { Navigate, createBrowserRouter } from 'react-router-dom'

import { LegacyRedirect,LegacySettingsEntry,ActivityEntry } from './LegacyRedirect'
import { AppShell } from './AppShell'
import {
  ActionRecordsRoute,CampusExceptionsRoute,SourcesRoute,
  PoliciesRoute,
 SharedAccessRoute,
 SharedBehaviorDetailsRoute,
 SharedReviewDetailsRoute,
  ActivityRoute,
  AuditRoute,
  AuditDetailsRoute,
  DevicesRoute,
  DiscoveryRoute,
  RouterObservationDetailsRoute,
  EndpointDetailsRoute,
  EventsRoute,
  EventDetailsRoute,
  IngestDiagnosticDetailsRoute,
  IpDetailsRoute,
  OverviewRoute,
  ReviewDetailsRoute,
  ShadowReviewSamplesRoute,
  RulesRoute,
  ShadowRunsRoute,
  ShadowRunDetailsRoute,
	CasesRoute,
	CaseDetailsRoute,
	OrganizationRoute,
	ActionsRoute,
	SecuritySettingsRoute,
} from './routePages'

export const router = createBrowserRouter([
  {
    path: '/',
    element: <AppShell />,
    children: [
      { index: true, element: <Navigate replace to="/overview" /> },
      { path: 'overview', element: <OverviewRoute /> },
      { path: 'activity', element: <ActivityEntry><ActivityRoute /></ActivityEntry> },
      { path: 'devices', element: <DevicesRoute /> },
      { path: 'discovery', element: <DiscoveryRoute /> },
      { path: 'discovery/routers/:assessmentId', element: <RouterObservationDetailsRoute /> },
      { path: 'devices/:endpointId', element: <EndpointDetailsRoute /> },
      { path: 'events', element: <EventsRoute /> },
      { path: 'events/:eventId', element: <EventDetailsRoute /> },
      { path: 'ingest', element: <LegacyRedirect to="/settings/sources" tab="diagnostics" /> },
      { path: 'ingest/diagnostics/:diagnosticId', element: <IngestDiagnosticDetailsRoute /> },
      { path: 'risks', element: <LegacyRedirect to="/cases" /> },
      { path: 'ips/:ip', element: <IpDetailsRoute /> },
      { path: 'review', element: <LegacyRedirect to="/cases" /> },
      { path: 'review/:caseId', element: <ReviewDetailsRoute /> },
	  { path: 'review-samples', element: <ShadowReviewSamplesRoute /> },
	  { path: 'cases', element: <CasesRoute /> },
	  { path: 'cases/:caseId', element: <CaseDetailsRoute /> },
      { path: 'shadow-runs', element: <ShadowRunsRoute /> },
      { path: 'shadow-runs/:runId', element: <ShadowRunDetailsRoute /> },
      { path: 'audit', element: <AuditRoute /> },
      { path: 'audit/:auditId', element: <AuditDetailsRoute /> },
      { path: 'shared-access', element: <SharedAccessRoute /> },
      { path: 'shared-access/observations/:observationId', element: <SharedBehaviorDetailsRoute /> },
      { path: 'shared-access/reviews/:id', element: <SharedReviewDetailsRoute /> },
      { path: 'policies', element: <PoliciesRoute /> },
      { path: 'settings/rules', element: <RulesRoute /> },
	  { path: 'settings/organization', element: <OrganizationRoute /> },
	  { path: 'actions', element: <ActionRecordsRoute /> },
      { path: 'policies/exceptions', element: <CampusExceptionsRoute /> },
      { path: 'settings/sources', element: <SourcesRoute /> },
      { path: 'settings/sources/diagnostics/:diagnosticId', element: <IngestDiagnosticDetailsRoute /> },
      { path: 'settings/actions', element: <LegacySettingsEntry kind="actions"><ActionsRoute /></LegacySettingsEntry> },
	  { path: 'settings/security', element: <LegacySettingsEntry kind="security"><SecuritySettingsRoute /></LegacySettingsEntry> },
    ],
  },
])
