/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActivityOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dpi/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDpiOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dpi/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDpiTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dpi/protocol-flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDpiProtocolFlows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dpi/fingerprint-conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDpiFingerprintConflicts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dpi/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDpiFlows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dpi/flows/{flow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDpiFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dpi/ips/{ip}/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIpDpiFlows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRisks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ips/{ip}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIpRisk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ips/{ip}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIpEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ips/{ip}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIpActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ips/{ip}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIpEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIngestStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIngestRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIngestDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIngestEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIngestErrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shadow/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listShadowRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reloadRules"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Permission: "risks:read" | "evidence:read" | "events:read" | "labels:create" | "shadow:read" | "audit:read" | "rules:reload" | "ingest:read" | "dpi:read";
        /** @enum {string} */
        Role: "viewer" | "reviewer" | "operator" | "admin";
        Session: {
            user: {
                id: string;
                name: string;
            };
            role: components["schemas"]["Role"];
            permissions: components["schemas"]["Permission"][];
        };
        /** @enum {string} */
        RiskLevel: "normal" | "suspicious" | "high" | "confirmed";
        /** @enum {string} */
        RecommendedAction: "record" | "shadow_watch" | "shadow_manual_review" | "shadow_confirm_review";
        /** @enum {string} */
        EvidenceSeverity: "low" | "medium" | "high";
        RiskSnapshot: {
            ip: string;
            score: number;
            level: components["schemas"]["RiskLevel"];
            confidence: number;
            window: string;
            evidence_ids: string[];
            summary: string;
            recommended_action: components["schemas"]["RecommendedAction"];
            /** Format: date-time */
            updated_at: string;
        };
        RiskListResponse: {
            items: components["schemas"]["RiskSnapshot"][];
            page: {
                limit: number;
                next_cursor: string | null;
                total: number;
            };
        };
        EventListResponse: {
            events: components["schemas"]["NormalizedEventSummary"][];
            page: {
                limit: number;
                next_cursor: string | null;
                total: number;
            };
        };
        Evidence: {
            evidence_id: string;
            ip: string;
            /** @enum {string} */
            type: "multi_user_agent" | "multi_ja3_ja4" | "ttl_clusters" | "domain_diversity" | "port_distribution" | "multi_device_fingerprint";
            window: string;
            score: number;
            confidence: number;
            severity: components["schemas"]["EvidenceSeverity"];
            reason: string;
            samples: string[];
            /** Format: date-time */
            created_at: string;
        };
        NormalizedEventSummary: {
            event_id: string;
            source?: string;
            /** @enum {string} */
            type: "flow" | "dns" | "tls" | "http" | "quic" | "device" | "alert";
            /** Format: date-time */
            timestamp: string;
            observer?: {
                [key: string]: unknown;
            };
            subject: {
                [key: string]: unknown;
            };
            flow: {
                [key: string]: unknown;
            };
            payload?: {
                [key: string]: unknown;
            };
            confidence: number;
            raw_ref?: {
                [key: string]: unknown;
            };
        };
        ActivityCount: {
            value: string;
            count: number;
            /** Format: date-time */
            last_seen?: string;
        };
        ActivityIpSummary: {
            ip: string;
            event_count: number;
            risk_level: components["schemas"]["RiskLevel"];
            score: number;
            top_domains: components["schemas"]["ActivityCount"][];
            /** Format: date-time */
            last_seen?: string;
        };
        ActivityOverview: {
            sensor_id: string;
            /** @enum {string} */
            window: "10m" | "1h" | "24h" | "latest-run";
            event_count: number;
            active_ip_count: number;
            access_object_count: number;
            active_risk_ip_count: number;
            /** Format: date-time */
            first_seen?: string;
            /** Format: date-time */
            last_seen?: string;
            event_type_counts: components["schemas"]["ActivityCount"][];
            protocol_counts: components["schemas"]["ActivityCount"][];
            top_domains: components["schemas"]["ActivityCount"][];
            top_http_hosts: components["schemas"]["ActivityCount"][];
            top_tls_sni: components["schemas"]["ActivityCount"][];
            top_user_agents: components["schemas"]["ActivityCount"][];
            top_tls_fingerprints: components["schemas"]["ActivityCount"][];
            top_dst_ports: components["schemas"]["ActivityCount"][];
            top_dst_ips: components["schemas"]["ActivityCount"][];
            top_source_ips: components["schemas"]["ActivityCount"][];
            top_active_risk_ips: components["schemas"]["ActivityIpSummary"][];
        };
        DpiOverview: {
            sensor_id: string;
            /** @enum {string} */
            window: "10m" | "1h" | "24h" | "latest-run";
            event_count: number;
            active_ip_count: number;
            protocol_flow_count: number;
            fingerprint_conflict_count: number;
            flow_sample_count: number;
            /** Format: date-time */
            first_seen?: string;
            /** Format: date-time */
            last_seen?: string;
        };
        DpiTrendPoint: {
            /** Format: date-time */
            time: string;
            active_devices: number;
            risk_ips: number;
            event_count: number;
            pps: number | null;
            bps_mbps: number | null;
            cps: number;
            estimated: boolean;
        };
        DpiProtocolFlow: {
            protocol: string;
            app_protocol: string;
            category: string;
            share_percent: number;
            event_count: number;
            bps_mbps?: number | null;
            top_apps: string[];
        };
        DpiFingerprintConflict: {
            id: string;
            ip: string;
            conflict_type: string;
            type_label: string;
            risk_level: components["schemas"]["RiskLevel"];
            confidence: number;
            device_count: number;
            detected_samples: string[];
            reason: string;
            /** Format: date-time */
            last_seen: string;
        };
        DpiFlowSample: {
            flow_id: string;
            event_id: string;
            /** Format: date-time */
            timestamp: string;
            sensor_id?: string;
            interface_name?: string;
            src_ip?: string;
            src_port?: number;
            dst_ip?: string;
            dst_port?: number;
            protocol?: string;
            app_protocol: string;
            user_agent?: string;
            tls_sni?: string;
            domain?: string;
            ja3?: string;
            ja4?: string;
            ttl?: number | null;
            ipid?: number | null;
            payload_summary: string;
        };
        DpiFlowListResponse: {
            items: components["schemas"]["DpiFlowSample"][];
            page: {
                limit: number;
                next_cursor: string | null;
                total: number;
            };
        };
        DpiFlowDetail: {
            flow: components["schemas"]["DpiFlowSample"];
            event: components["schemas"]["NormalizedEventSummary"];
            risk: components["schemas"]["RiskSnapshot"];
            evidence: components["schemas"]["Evidence"][];
        };
        ActivityAccess: {
            /** Format: date-time */
            timestamp: string;
            event_id: string;
            type: string;
            target_kind: string;
            target: string;
            method?: string;
            user_agent?: string;
            dst_ip?: string;
            dst_port?: number;
            proto?: string;
        };
        IpActivityProfile: {
            ip: string;
            window: string;
            event_count: number;
            /** Format: date-time */
            first_seen?: string;
            /** Format: date-time */
            last_seen?: string;
            event_type_counts: components["schemas"]["ActivityCount"][];
            protocol_counts: components["schemas"]["ActivityCount"][];
            top_domains: components["schemas"]["ActivityCount"][];
            top_http_hosts: components["schemas"]["ActivityCount"][];
            top_tls_sni: components["schemas"]["ActivityCount"][];
            top_user_agents: components["schemas"]["ActivityCount"][];
            top_tls_fingerprints: components["schemas"]["ActivityCount"][];
            top_dst_ports: components["schemas"]["ActivityCount"][];
            top_dst_ips: components["schemas"]["ActivityCount"][];
            recent_accesses: components["schemas"]["ActivityAccess"][];
        };
        Collector: {
            /** @enum {string} */
            kind: "suricata" | "zeek" | "af_xdp" | "dpdk" | "pcap" | "unknown";
            version?: string;
            interface?: string;
        };
        IngestDiagnostic: {
            /** @enum {string} */
            schema_version: "v1";
            diagnostic_id: string;
            /** Format: date-time */
            timestamp: string;
            sensor_id: string;
            collector: components["schemas"]["Collector"];
            /** @enum {string} */
            stage: "capture" | "decode" | "normalize" | "evidence" | "risk";
            /** @enum {string} */
            type: "stats" | "skip" | "parse_error" | "service_status" | "event_type_count";
            /** @enum {string} */
            severity: "info" | "warning" | "error";
            summary: string;
            counters?: {
                [key: string]: number;
            };
            by_type?: {
                [key: string]: number;
            };
            raw_ref?: {
                [key: string]: unknown;
            };
            details?: {
                [key: string]: unknown;
            };
        };
        IngestStatus: {
            sensor_id: string;
            collector: components["schemas"]["Collector"];
            /** @enum {string} */
            storage_mode: "file" | "db" | "dual";
            latest_run_id?: string;
            /** Format: date-time */
            latest_run_at?: string;
            healthy: boolean;
            /** @enum {string} */
            severity: "info" | "warning" | "error";
            summary: string;
            last_counters: {
                [key: string]: number;
            };
            last_event_type_dist: {
                [key: string]: number;
            };
        };
        EventTypeCount: {
            type: string;
            count: number;
        };
        /** @enum {string} */
        LabelKind: "confirmed_proxy" | "false_positive" | "benign" | "needs_more_data";
        CreateLabelRequest: {
            /** @enum {string} */
            target_type: "ip" | "risk_snapshot" | "evidence";
            target_id: string;
            label: components["schemas"]["LabelKind"];
            reason: string;
            evidence_ids: string[];
        };
        Label: components["schemas"]["CreateLabelRequest"] & {
            label_id: string;
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        ShadowRun: {
            run_id: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at: string;
            sensor_id: string;
            previous_offset: number;
            new_offset: number;
            truncated: boolean;
            normalized: {
                read: number;
                emitted: number;
                skipped: number;
                malformed: number;
            };
            evidence_count: number;
            risk_count: number;
            risk_list_count: number;
        };
        AuditLog: {
            audit_id: string;
            actor: string;
            action: string;
            target: string;
            outcome: string;
            /** Format: date-time */
            created_at: string;
        };
        Overview: {
            level_counts: {
                normal: number;
                suspicious: number;
                high: number;
                confirmed: number;
            };
            pending_reviews: number;
            latest_shadow_run: components["schemas"]["ShadowRun"];
            throughput: {
                events: number;
                evidence: number;
                risks: number;
            };
            top_evidence: {
                type: string;
                count: number;
            }[];
        };
        RuleReloadResult: {
            /** @enum {string} */
            status: "accepted" | "disabled";
            /** @enum {string} */
            mode: "shadow";
            /** Format: date-time */
            requested_at: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Operation is disabled or not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IpPath: string;
        LevelQuery: components["schemas"]["RiskLevel"];
        EventFilterQuery: string;
        EventTypeQuery: string;
        SensorIdQuery: string;
        FromQuery: string;
        ToQuery: string;
        WindowQuery: "10m" | "1h" | "24h";
        SrcIpQuery: string;
        DstIpQuery: string;
        DomainQuery: string;
        UserAgentQuery: string;
        /** @description JA3/JA4 fingerprint value from normalized event payload. */
        FingerprintQuery: string;
        PortQuery: number;
        ProtoQuery: string;
        LimitQuery: number;
        CursorQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current mock or authenticated session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operations overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getActivityOverview: {
        parameters: {
            query?: {
                sensor_id?: string;
                window?: "10m" | "1h" | "24h";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated access posture and client feature overview for the observed domain. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOverview"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getDpiOverview: {
        parameters: {
            query?: {
                sensor_id?: string;
                window?: "10m" | "1h" | "24h";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DPI metadata overview derived from normalized events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DpiOverview"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listDpiTrends: {
        parameters: {
            query?: {
                sensor_id?: string;
                window?: "1h" | "24h";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DPI event and device trend points. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        points: components["schemas"]["DpiTrendPoint"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listDpiProtocolFlows: {
        parameters: {
            query?: {
                sensor_id?: string;
                window?: "10m" | "1h" | "24h";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Protocol flow distribution based on normalized event metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DpiProtocolFlow"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listDpiFingerprintConflicts: {
        parameters: {
            query?: {
                sensor_id?: string;
                window?: "10m" | "1h" | "24h";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Standardized fingerprint conflicts observed in a window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DpiFingerprintConflict"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listDpiFlows: {
        parameters: {
            query?: {
                q?: components["parameters"]["EventFilterQuery"];
                type?: components["parameters"]["EventTypeQuery"];
                sensor_id?: components["parameters"]["SensorIdQuery"];
                from?: components["parameters"]["FromQuery"];
                to?: components["parameters"]["ToQuery"];
                window?: components["parameters"]["WindowQuery"];
                src_ip?: components["parameters"]["SrcIpQuery"];
                dst_ip?: components["parameters"]["DstIpQuery"];
                domain?: components["parameters"]["DomainQuery"];
                user_agent?: components["parameters"]["UserAgentQuery"];
                /** @description JA3/JA4 fingerprint value from normalized event payload. */
                fingerprint?: components["parameters"]["FingerprintQuery"];
                port?: components["parameters"]["PortQuery"];
                proto?: components["parameters"]["ProtoQuery"];
                limit?: components["parameters"]["LimitQuery"];
                cursor?: components["parameters"]["CursorQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered DPI flow samples built from normalized events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DpiFlowListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getDpiFlow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DPI flow detail with normalized event, evidence and risk context. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DpiFlowDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listIpDpiFlows: {
        parameters: {
            query?: {
                q?: components["parameters"]["EventFilterQuery"];
                type?: components["parameters"]["EventTypeQuery"];
                sensor_id?: components["parameters"]["SensorIdQuery"];
                from?: components["parameters"]["FromQuery"];
                to?: components["parameters"]["ToQuery"];
                window?: components["parameters"]["WindowQuery"];
                dst_ip?: components["parameters"]["DstIpQuery"];
                domain?: components["parameters"]["DomainQuery"];
                user_agent?: components["parameters"]["UserAgentQuery"];
                /** @description JA3/JA4 fingerprint value from normalized event payload. */
                fingerprint?: components["parameters"]["FingerprintQuery"];
                port?: components["parameters"]["PortQuery"];
                proto?: components["parameters"]["ProtoQuery"];
                limit?: components["parameters"]["LimitQuery"];
                cursor?: components["parameters"]["CursorQuery"];
            };
            header?: never;
            path: {
                ip: components["parameters"]["IpPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DPI flow samples for one source IP. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DpiFlowListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listRisks: {
        parameters: {
            query?: {
                level?: components["parameters"]["LevelQuery"];
                q?: string;
                sensor_id?: string;
                from?: string;
                to?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered risk snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getIpRisk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: components["parameters"]["IpPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current risk snapshot for an IP. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getIpEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: components["parameters"]["IpPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence timeline for an IP. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        evidence: components["schemas"]["Evidence"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getIpActivity: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                ip: components["parameters"]["IpPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated access and client feature profile for an IP. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpActivityProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getIpEvents: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                ip: components["parameters"]["IpPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized event summaries for an IP. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["NormalizedEventSummary"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                q?: string;
                type?: string;
                sensor_id?: string;
                from?: string;
                to?: string;
                window?: "10m" | "1h" | "24h";
                src_ip?: string;
                dst_ip?: string;
                domain?: string;
                user_agent?: string;
                /** @description JA3/JA4 fingerprint value from normalized event payload. */
                fingerprint?: string;
                port?: number;
                proto?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered normalized event samples. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One normalized event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NormalizedEventSummary"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getIngestStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current collector and normalization status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestStatus"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listIngestRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collector and risk analysis runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs: components["schemas"]["ShadowRun"][];
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listIngestDiagnostics: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collector diagnostics and normalization statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        diagnostics: components["schemas"]["IngestDiagnostic"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listIngestEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest event type distribution. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        event_types: components["schemas"]["EventTypeCount"][];
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listIngestErrors: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Warning or error diagnostics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        diagnostics: components["schemas"]["IngestDiagnostic"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    createLabel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLabelRequest"];
            };
        };
        responses: {
            /** @description Created label. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    listShadowRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shadow mode run summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs: components["schemas"]["ShadowRun"][];
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        logs: components["schemas"]["AuditLog"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    reloadRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule reload accepted in shadow mode. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleReloadResult"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
}
