/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRisks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ips/{ip}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIpRisk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ips/{ip}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIpEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ips/{ip}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIpEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shadow/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listShadowRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reloadRules"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Permission: "risks:read" | "evidence:read" | "events:read" | "labels:create" | "shadow:read" | "audit:read" | "rules:reload";
        /** @enum {string} */
        Role: "viewer" | "reviewer" | "operator" | "admin";
        Session: {
            user: {
                id: string;
                name: string;
            };
            role: components["schemas"]["Role"];
            permissions: components["schemas"]["Permission"][];
        };
        /** @enum {string} */
        RiskLevel: "normal" | "suspicious" | "high" | "confirmed";
        /** @enum {string} */
        RecommendedAction: "record" | "shadow_watch" | "shadow_manual_review" | "shadow_confirm_review";
        /** @enum {string} */
        EvidenceSeverity: "low" | "medium" | "high";
        RiskSnapshot: {
            ip: string;
            score: number;
            level: components["schemas"]["RiskLevel"];
            confidence: number;
            window: string;
            evidence_ids: string[];
            summary: string;
            recommended_action: components["schemas"]["RecommendedAction"];
            /** Format: date-time */
            updated_at: string;
        };
        RiskListResponse: {
            items: components["schemas"]["RiskSnapshot"][];
            page: {
                limit: number;
                next_cursor: string | null;
                total: number;
            };
        };
        Evidence: {
            evidence_id: string;
            ip: string;
            /** @enum {string} */
            type: "multi_user_agent" | "multi_ja3_ja4" | "ttl_clusters" | "domain_diversity" | "port_distribution" | "multi_device_fingerprint";
            window: string;
            score: number;
            confidence: number;
            severity: components["schemas"]["EvidenceSeverity"];
            reason: string;
            samples: string[];
            /** Format: date-time */
            created_at: string;
        };
        NormalizedEventSummary: {
            event_id: string;
            source?: string;
            /** @enum {string} */
            type: "flow" | "dns" | "tls" | "http" | "quic" | "device" | "alert";
            /** Format: date-time */
            timestamp: string;
            observer?: {
                [key: string]: unknown;
            };
            subject: {
                [key: string]: unknown;
            };
            flow: {
                [key: string]: unknown;
            };
            payload?: {
                [key: string]: unknown;
            };
            confidence: number;
            raw_ref?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        LabelKind: "confirmed_proxy" | "false_positive" | "benign" | "needs_more_data";
        CreateLabelRequest: {
            /** @enum {string} */
            target_type: "ip" | "risk_snapshot" | "evidence";
            target_id: string;
            label: components["schemas"]["LabelKind"];
            reason: string;
            evidence_ids: string[];
        };
        Label: components["schemas"]["CreateLabelRequest"] & {
            label_id: string;
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        ShadowRun: {
            run_id: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at: string;
            sensor_id: string;
            previous_offset: number;
            new_offset: number;
            truncated: boolean;
            normalized: {
                read: number;
                emitted: number;
                skipped: number;
                malformed: number;
            };
            evidence_count: number;
            risk_count: number;
            risk_list_count: number;
        };
        AuditLog: {
            audit_id: string;
            actor: string;
            action: string;
            target: string;
            outcome: string;
            /** Format: date-time */
            created_at: string;
        };
        Overview: {
            level_counts: {
                normal: number;
                suspicious: number;
                high: number;
                confirmed: number;
            };
            pending_reviews: number;
            latest_shadow_run: components["schemas"]["ShadowRun"];
            throughput: {
                events: number;
                evidence: number;
                risks: number;
            };
            top_evidence: {
                type: string;
                count: number;
            }[];
        };
        RuleReloadResult: {
            /** @enum {string} */
            status: "accepted" | "disabled";
            /** @enum {string} */
            mode: "shadow";
            /** Format: date-time */
            requested_at: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Operation is disabled or not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IpPath: string;
        LevelQuery: components["schemas"]["RiskLevel"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current mock or authenticated session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operations overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listRisks: {
        parameters: {
            query?: {
                level?: components["parameters"]["LevelQuery"];
                q?: string;
                sensor_id?: string;
                from?: string;
                to?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered risk snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getIpRisk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: components["parameters"]["IpPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current risk snapshot for an IP. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getIpEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: components["parameters"]["IpPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence timeline for an IP. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        evidence: components["schemas"]["Evidence"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getIpEvents: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                ip: components["parameters"]["IpPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized event summaries for an IP. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["NormalizedEventSummary"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    createLabel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLabelRequest"];
            };
        };
        responses: {
            /** @description Created label. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    listShadowRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shadow mode run summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs: components["schemas"]["ShadowRun"][];
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        logs: components["schemas"]["AuditLog"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    reloadRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule reload accepted in shadow mode. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleReloadResult"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
}
