import { test, expect } from '@playwright/test'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
for(const width of [390,1280,1440]) test(`policy forms and inventory ${width}`,async({page})=>{
 await page.setViewportSize({width,height:width===390?844:width===1280?800:900})
 await page.goto('/policies')
 await expect(page.getByText('教职工设备配额',{exact:true})).toBeVisible()
 await page.getByLabel('试算账号').fill('staff-001')
 await page.getByRole('button',{name:'策略试算',exact:true}).click()
 await expect(page.getByText('覆盖不足，无法完整判断在线设备数',{exact:true})).toBeVisible()
 const folder=path.resolve('test-results/policy-visuals');await mkdir(folder,{recursive:true})
 await page.screenshot({path:path.join(folder,`page-${width}.png`),fullPage:true,animations:'disabled'})
 await page.getByRole('button',{name:'新建设备配额策略',exact:true}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await expect(page.getByRole('dialog').getByRole('heading',{name:'策略信息',exact:true})).toBeVisible()
 await expect(page.getByRole('dialog').locator('.ant-steps').getByText('配额超限认定条件',{exact:true})).toBeVisible()
 await expect(page.getByRole('dialog').locator('.ant-steps').getByText('配额超限处理动作',{exact:true})).toBeVisible()
 await page.getByRole('dialog').getByLabel('策略名称').fill('办公室防代理策略')
 await page.getByRole('dialog').getByLabel('选择产品').click()
 await expect(page.getByText('办公室上网产品 (office-product-001)',{exact:true}).last()).toBeVisible()
 await page.keyboard.press('Escape')
 await page.getByRole('dialog').getByRole('button',{name:'下一步'}).click()
 await expect(page.getByRole('dialog').getByText('设备数量满足任意一项就会触发',{exact:true})).toBeVisible()
 await page.getByRole('dialog').getByLabel('全部设备数大于').fill('3')
 await page.getByRole('dialog').getByLabel('电脑数量大于').fill('2')
 await page.getByRole('dialog').getByLabel('移动设备数量大于').fill('2')
 await page.getByRole('dialog').getByRole('button',{name:'下一步'}).click()
 await page.getByRole('dialog').getByRole('switch',{name:'强制下线'}).click()
 await expect(page.getByRole('dialog').getByLabel('强制下线执行设备')).toHaveCount(0)
 await expect(page.getByRole('dialog').locator('.policy-action-card').filter({hasText:'强制下线'})).toContainText('同时消息提醒用户')
 const probe=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+2,bad:[...document.querySelectorAll('.policies-page .ant-btn,.policies-page .ant-tag,.policy-stage .ant-btn')].filter(e=>{const c=getComputedStyle(e);return c.whiteSpace!=='nowrap'||c.flexShrink!=='0'}).map(e=>e.textContent),card:getComputedStyle(document.querySelector('.policies-page .ant-card')!).borderRadius,padding:getComputedStyle(document.querySelector('.policies-page .ant-card-body')!).paddingTop,columns:getComputedStyle(document.querySelector('.policy-form-grid')!).gridTemplateColumns}))
 await writeFile(path.join(folder,`dom-${width}.json`),JSON.stringify(probe,null,2))
 expect(probe.overflow).toBe(false);expect(probe.bad).toEqual([]);expect(probe.card).toBe('8px');expect(probe.padding).toBe(width===390?'14px':'20px')
 await expect(page.getByRole('dialog').getByRole('button',{name:'保存设置'})).toBeInViewport()
 await page.screenshot({path:path.join(folder,`form-${width}.png`),animations:'disabled'})
})
