import {useSession} from '../shared/api/queries'
import {can} from '../shared/auth/permissions'
import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, Button, Form, Input, InputNumber, Modal, Select, Space, Switch, Table, Tabs, Tag, Typography, message } from 'antd'
import { Link } from 'react-router-dom'
import { request } from '../shared/api/client'
import { RouterObservationsPanel } from './RouterObservationsPanel'

type Source = {id:string;name:string;node:string;site:string;domain:string;address:string;snmp_version:string;username?:string;interval_seconds:number;enabled:boolean;config_version:number}
type Observation = {id:string;ip?:string;mac?:string;name?:string;origin:string;port?:string;vlan?:string;observed_at:string;valid_until:string;explanation:string;device_type?:string;capabilities?:string[]}
type Device = {id:string;primary_ip?:string;addresses:string[];mac?:string;name?:string;device_type?:string;capabilities:string[];protocols:string[];confidence:string;first_seen:string;last_seen:string;current:boolean;evidence_count:number;endpoint_id?:string;observations:Observation[]}
type ScanProfile = {id:string;node:string;site:string;domain:string;version:number;trial_version:number;enabled:boolean;config:{allow:string[];exclude:string[];addresses:string[];interface?:string;protocols:string[];sensitive:boolean;interval_seconds:number}}
type Task = {id:string;source_id:string;status:string;created_at:string;error?:string;result?:{tables?:{name:string;count:number;complete:boolean;error?:string}[]}}
const statuses:Record<string,string>={pending:'等待采集',running:'采集中',complete:'已完成',partial:'部分完成',failed:'失败',cancelled:'已停止'}
const origins:Record<string,string>={fdb:'交换机 MAC 表',neighbor:'网关邻居表',lldp:'LLDP 邻居',cdp:'CDP 邻居',dhcp:'DHCP ACK',arp:'ARP',ndp:'IPv6 NDP',ieee1905_client:'IEEE 1905 客户关联',dns_sd:'mDNS / DNS-SD',ssdp:'SSDP 响应／公告',ws_discovery:'WS-Discovery 响应',active:'探测响应'}
const deviceTypes:Record<string,string>={router:'路由器',switch:'交换机',access_point:'接入点',gateway:'网关',media_device:'媒体设备',camera:'摄像头',printer:'打印机'}
const capabilityNames:Record<string,string>={printing:'打印服务',scanning:'扫描服务',casting:'投屏服务',network_video:'网络视频',routing:'路由服务',media_rendering:'媒体播放'}
export function DiscoveryPage(){
 const session=useSession();const manage=can(session.data,'integrations:write')
 const client=useQueryClient();const [form]=Form.useForm();const [editing,setEditing]=useState<Source|null>();const [page,setPage]=useState(1);const [passivePage,setPassivePage]=useState(1);const [search,setSearch]=useState('');const [deviceType,setDeviceType]=useState('');const [capability,setCapability]=useState('');const [detail,setDetail]=useState<Device>();const [saving,setSaving]=useState(false)
 const options={refetchInterval:()=>document.visibilityState==='visible'?15000:false,refetchIntervalInBackground:false}
 const sources=useQuery({queryKey:['discovery','sources'],queryFn:()=>request<{items:Source[]}>('/discovery/sources'),...options})
 const devices=useQuery({queryKey:['discovery','devices','infrastructure',page],queryFn:()=>request<{items:Device[];total:number}>(`/discovery/devices?mode=infrastructure&window=24h&limit=20&offset=${(page-1)*20}`),...options})
 const passiveParams=new URLSearchParams({mode:'passive',window:'24h',limit:'20',offset:String((passivePage-1)*20)});if(search)passiveParams.set('search',search);if(deviceType)passiveParams.set('type',deviceType);if(capability)passiveParams.set('capability',capability)
 const passiveDevices=useQuery({queryKey:['discovery','devices','passive',passivePage,search,deviceType,capability],queryFn:()=>request<{items:Device[];total:number}>(`/discovery/devices?${passiveParams}`),...options})
 const tasks=useQuery({queryKey:['discovery','tasks'],queryFn:()=>request<{items:Task[]}>('/discovery/tasks'),...options})
 const [scanForm]=Form.useForm();const [scanOpen,setScanOpen]=useState(false);const[scanEditing,setScanEditing]=useState<ScanProfile>();const [preview,setPreview]=useState<number>();
 const profiles=useQuery({queryKey:['discovery','profiles'],queryFn:()=>request<{items:ScanProfile[]}>('/discovery/scan-profiles'),...options})
 const scanConfig=(v:Record<string,unknown>)=>({allow:String(v.allow??'').split(/[,\s]+/).filter(Boolean),exclude:String(v.exclude??'').split(/[,\s]+/).filter(Boolean),addresses:String(v.addresses??'').split(/[,\s]+/).filter(Boolean),interface:v.interface??'',protocols:v.protocols??['icmp'],sensitive:v.sensitive??false,interval_seconds:Number(v.interval_seconds??86400)})
 async function previewScan(){try{const v=await scanForm.validateFields();const result=await request<{total:number}>('/discovery/preview',{method:'POST',body:JSON.stringify(scanConfig(v))});setPreview(result.total)}catch(e){void message.error(String(e))}}
 async function saveScan(){try{const v=await scanForm.validateFields();await request('/discovery/scan-profiles',{method:'POST',body:JSON.stringify({id:v.id,node:v.node,site:v.site,domain:v.domain,config:scanConfig(v),version:scanEditing?.version??0})});setScanOpen(false);void refresh()}catch(e){void message.error(String(e))}}
 const summary=useQuery({queryKey:['discovery','summary'],queryFn:()=>request<{window:string;infrastructure:number;active_responses:number;pending_association:number;passive_devices:number;service_devices:number;linked_endpoints:number;last_materialized_at?:string;materializer_status?:string;materializer_error?:string}>('/discovery/summary'),...options})
 const nodes=useQuery({queryKey:['discovery','nodes'],queryFn:()=>request<{items:{node:string;available:boolean}[]}>('/discovery/nodes'),...options})
 const refresh=()=>client.invalidateQueries({queryKey:['discovery']})
 async function action(path:string){try{await request(path,{method:'POST',body:'{}'});void refresh()}catch(e){void message.error(String(e))}}
 function edit(s:Source|null){setEditing(s);form.resetFields();form.setFieldsValue(s??{snmp_version:'3',interval_seconds:300,enabled:false})}
 async function save(){const v=await form.validateFields();setSaving(true);try{const{community,auth,privacy,...source}=v;await request('/discovery/sources',{method:'POST',body:JSON.stringify({source:{...source,config_version:editing?.config_version??0},secret:{community,auth,privacy},expected_version:editing?.config_version??0})});setEditing(undefined);void refresh()}catch(e){void message.error(String(e))}finally{setSaving(false)}}
 const cols=[{title:'名称',key:'name',render:(_:unknown,d:Device)=><div className="discovery-name-cell">{d.name&&<strong>{d.name}</strong>}{d.endpoint_id&&<Link to={`/devices/${encodeURIComponent(d.endpoint_id)}`}>查看终端画像</Link>}</div>},{title:'IP',key:'ip',width:155,render:(_:unknown,d:Device)=><span className="discovery-identifier">{d.primary_ip??''}</span>},{title:'MAC',key:'mac',width:160,render:(_:unknown,d:Device)=><span className="discovery-identifier">{d.mac??''}</span>},{title:'类型／能力',key:'type',render:(_:unknown,d:Device)=><Space wrap>{d.device_type&&<Tag color={d.confidence==='confirmed'?'blue':undefined}>{deviceTypes[d.device_type]??d.device_type}</Tag>}{d.capabilities.map(c=><Tag key={c}>{capabilityNames[c]??c}</Tag>)}</Space>},{title:'协议依据',key:'source',render:(_:unknown,d:Device)=><Space wrap>{d.protocols.map(o=><Tag key={o}>{origins[o]??o}</Tag>)}</Space>},{title:'最后观测',key:'time',width:180,render:(_:unknown,d:Device)=><div>{new Date(d.last_seen).toLocaleString('zh-CN',{hour12:false})}<Typography.Text type="secondary" className="discovery-validity">{d.current?'协议记录有效':'协议记录已过期'}</Typography.Text></div>},{title:'操作',key:'action',fixed:'right' as const,width:100,render:(_:unknown,d:Device)=><Button type="link" onClick={()=>setDetail(d)}>查看证据</Button>}]
 const deviceCards=(items:Device[]|undefined,currentPage:number,setCurrentPage:(value:number)=>void,total:number)=><div className="discovery-mobile">{items?.map(d=><article className="discovery-card" key={d.id}><strong>{d.name||d.primary_ip||d.mac}</strong>{d.name&&d.primary_ip&&<div className="discovery-identifier">{d.primary_ip}</div>}{d.mac&&<div className="discovery-identifier">{d.mac}</div>}<div className="discovery-card-tags"><Space wrap>{d.device_type&&<Tag>{deviceTypes[d.device_type]??d.device_type}</Tag>}{d.capabilities.map(c=><Tag key={c}>{capabilityNames[c]??c}</Tag>)}</Space></div><div>{d.protocols.map(o=>origins[o]??o).join('、')}</div><Typography.Text type="secondary">最后观测 {new Date(d.last_seen).toLocaleString('zh-CN',{hour12:false})}</Typography.Text><Space wrap>{d.endpoint_id&&<Link to={`/devices/${encodeURIComponent(d.endpoint_id)}`}>查看终端画像</Link>}<Button onClick={()=>setDetail(d)}>查看证据</Button></Space></article>)}<Space wrap><Button disabled={currentPage===1} onClick={()=>setCurrentPage(currentPage-1)}>上一页</Button><Button disabled={currentPage*20>=total} onClick={()=>setCurrentPage(currentPage+1)}>下一页</Button></Space></div>
 return <main className="page discovery-page"><header className="discovery-page-header"><div><Typography.Title level={3}>网络设备发现</Typography.Title><Typography.Text type="secondary">基础设施记录与流量观测分别保存；表项读取不代表当前在线。</Typography.Text></div><Space wrap><Link to="/devices">返回终端画像</Link><Button onClick={()=>void refresh()}>刷新</Button></Space></header>
 {(sources.error||devices.error||passiveDevices.error||tasks.error||profiles.error||nodes.error||summary.error)&&<Alert type="error" title="读取发现数据失败" description={String(sources.error||devices.error||passiveDevices.error||tasks.error||profiles.error||nodes.error||summary.error)}/>}
 <section className="surface">{summary.data&&<div className="discovery-toolbar"><Typography.Text type="secondary">最近 24 小时观测；不代表设备当前在线</Typography.Text><Space wrap><span>被动设备 {summary.data.passive_devices}</span><span>服务设备 {summary.data.service_devices}</span><span>基础设施 {summary.data.infrastructure}</span><span>已关联终端 {summary.data.linked_endpoints}</span>{summary.data.last_materialized_at&&<span>物化于 {new Date(summary.data.last_materialized_at).toLocaleTimeString('zh-CN',{hour12:false})}</span>}</Space></div>} {summary.data?.materializer_error&&<Alert type="error" title="被动发现物化异常" description={summary.data.materializer_error}/>}<Tabs defaultActiveKey="passive" items={[
 {key:'routers',label:'路由识别',children:<RouterObservationsPanel/>},
 {key:'passive',label:'被动发现设备',children:<><div className="discovery-filters"><Input.Search allowClear placeholder="搜索名称、IP 或 MAC" value={search} onChange={event=>{setSearch(event.target.value);setPassivePage(1)}}/><Select allowClear placeholder="设备类型" value={deviceType||undefined} onChange={value=>{setDeviceType(value??'');setPassivePage(1)}} options={[{value:'printer',label:'打印机'},{value:'camera',label:'摄像头'},{value:'gateway',label:'网关'},{value:'media_device',label:'媒体设备'}]}/><Select allowClear placeholder="服务能力" value={capability||undefined} onChange={value=>{setCapability(value??'');setPassivePage(1)}} options={Object.entries(capabilityNames).map(([value,label])=>({value,label}))}/></div><div className="discovery-desktop"><Table rowKey="id" columns={cols} dataSource={passiveDevices.data?.items??[]} pagination={{current:passivePage,total:passiveDevices.data?.total??0,pageSize:20,onChange:setPassivePage}} locale={{emptyText:'最近 24 小时没有被动发现记录'}} scroll={{x:1080}}/></div>{deviceCards(passiveDevices.data?.items,passivePage,setPassivePage,passiveDevices.data?.total??0)}</>},
 {key:'devices',label:'基础设施发现',children:<><div className="discovery-desktop"><Table rowKey="id" columns={cols} dataSource={devices.data?.items??[]} pagination={{current:page,total:devices.data?.total??0,pageSize:20,onChange:setPage}} locale={{emptyText:'最近 24 小时没有基础设施记录'}} scroll={{x:1080}}/></div>{deviceCards(devices.data?.items,page,setPage,devices.data?.total??0)}</>},
 {key:'sources',label:'基础设施接入',children:<><Button disabled={!manage} onClick={()=>edit(null)}>新增接入源</Button><div className="discovery-source-list">{sources.data?.items.map(s=><article className="discovery-card" key={s.id}><strong>{s.name||s.address}</strong><div>{s.address} · SNMP {s.snmp_version} · {s.site} / {s.domain}</div><div>采集节点 {s.node} · 每 {s.interval_seconds} 秒 · {s.enabled?'定时采集':'手动采集'}</div><Space wrap><Button disabled={!manage} onClick={()=>edit(s)}>编辑</Button><Button disabled={!manage} onClick={()=>void action(`/discovery/sources/${encodeURIComponent(s.id)}/poll`)}>测试并采集</Button></Space></article>)}</div></>},
 {key:'scan',label:'主动发现',children:<><Alert type="info" title="默认关闭；仅探测明确指定范围" description="先配置范围并预览，手动试扫完成后才能开启定时。IPv6 仅使用已发现或明确填写的地址。"/><Button disabled={!manage} onClick={()=>{scanForm.resetFields();setScanEditing(undefined);setPreview(undefined);setScanOpen(true)}}>新增探测配置</Button><div className="discovery-source-list">{profiles.data?.items.map(p=><article className="discovery-card" key={p.id}><strong>{p.id}</strong><div>{p.node} · {p.enabled?'定时已启用':'定时关闭'}</div><Space wrap><Button disabled={!manage} onClick={()=>{setScanEditing(p);scanForm.setFieldsValue({...p,...p.config,allow:p.config.allow.join(', '),exclude:p.config.exclude.join(', '),addresses:p.config.addresses.join(', ')});setPreview(undefined);setScanOpen(true)}}>编辑范围</Button><Button disabled={!manage} onClick={()=>void action(`/discovery/scan-profiles/${encodeURIComponent(p.id)}/trial`)}>手动试扫</Button><Button disabled={!manage||(!p.enabled&&p.trial_version!==p.version)} onClick={()=>{void request(`/discovery/scan-profiles/${encodeURIComponent(p.id)}/schedule`,{method:'POST',body:JSON.stringify({enabled:!p.enabled,version:p.version})}).then(refresh).catch(e=>message.error(String(e)))}}>{p.enabled?'关闭定时':'开启定时'}</Button></Space></article>)}</div></>},
 {key:'tasks',label:'任务与诊断',children:<div className="discovery-source-list">{nodes.data?.items.map(n=><div key={n.node}>采集节点 {n.node} · {n.available?'任务服务就绪':'任务服务心跳超时'}</div>)}{tasks.data?.items.map(t=><article className="discovery-card" key={t.id}><strong>{t.source_id}</strong><div>{statuses[t.status]??t.status} · {new Date(t.created_at).toLocaleString('zh-CN',{hour12:false})}</div>{t.error&&<Alert type="error" title={t.error}/>} {t.result?.tables?.map(v=><div key={v.name}>{v.name} · {v.count} 条 {v.error}</div>)}{['pending','running'].includes(t.status)&&<Button disabled={!manage} onClick={()=>void action(`/discovery/tasks/${encodeURIComponent(t.id)}/stop`)}>停止</Button>}</article>)}</div>}
 ]}/></section>
 <Modal title="配置主动发现" open={scanOpen} onCancel={()=>setScanOpen(false)} onOk={()=>void saveScan()} okButtonProps={{disabled:preview===undefined}}><Form form={scanForm} layout="vertical" onValuesChange={()=>setPreview(undefined)} initialValues={{protocols:['icmp'],sensitive:false}}>{[{name:'id',label:'配置标识'},{name:'node',label:'采集节点'},{name:'site',label:'站点'},{name:'domain',label:'网络范围'},{name:'allow',label:'允许网段（CIDR，逗号分隔）'}].map(f=><Form.Item key={f.name} name={f.name} label={f.label} rules={[{required:true}]}>{f.name==='node'?<Select showSearch options={nodes.data?.items.map(n=>({value:n.node,label:n.node}))}/>:<Input disabled={f.name==='id'&&!!scanEditing}/>}</Form.Item>)}<Form.Item name="exclude" label="排除地址／网段（CIDR）"><Input/></Form.Item><Form.Item name="addresses" label="指定 IPv6 地址"><Input/></Form.Item><Form.Item name="interface" label="本地链路接口"><Input/></Form.Item><Form.Item name="sensitive" label="工控／敏感范围" valuePropName="checked"><Switch/></Form.Item><Form.Item name="interval_seconds" label="定时间隔（秒）" initialValue={86400}><InputNumber min={3600} max={604800}/></Form.Item><Form.Item name="protocols" label="探测协议"><Select mode="multiple" options={['icmp','arp','ndp','ipp','ipps','ssdp','onvif'].map(value=>({value,label:value.toUpperCase()}))}/></Form.Item><Button onClick={()=>void previewScan()}>预览目标数</Button>{preview!==undefined&&<Typography.Paragraph>显式目标 {preview} 个，保存后保持关闭。</Typography.Paragraph>}</Form></Modal>
 <Modal title={editing?'编辑接入源':'新增接入源'} open={editing!==undefined} onCancel={()=>setEditing(undefined)} onOk={()=>void save()} confirmLoading={saving} destroyOnHidden><Form form={form} layout="vertical">
 {([{name:'id',label:'接入源标识'},{name:'name',label:'名称'},{name:'address',label:'管理 IP'},{name:'node',label:'采集节点'},{name:'site',label:'站点'},{name:'domain',label:'二层网络范围'}]).map(f=><Form.Item key={f.name} name={f.name} label={f.label} rules={[{required:true}]}>{f.name==='node'?<Select showSearch options={nodes.data?.items.map(n=>({value:n.node,label:n.node+(n.available?'':'（心跳超时）')}))}/>:<Input disabled={f.name==='id'&&!!editing}/>}</Form.Item>)}
 <Form.Item name="snmp_version" label="SNMP 版本"><Select options={[{value:'3',label:'SNMPv3 authPriv（SHA-256 / AES）'},{value:'2c',label:'SNMPv2c 只读'}]}/></Form.Item>
 <Form.Item noStyle shouldUpdate={(a,b)=>a.snmp_version!==b.snmp_version}>{({getFieldValue})=>getFieldValue('snmp_version')==='3'?<><Form.Item name="username" label="用户名" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="auth" label="认证口令"><Input.Password autoComplete="new-password"/></Form.Item><Form.Item name="privacy" label="加密口令"><Input.Password autoComplete="new-password"/></Form.Item></>:<Form.Item name="community" label="只读 Community"><Input.Password autoComplete="new-password"/></Form.Item>}</Form.Item>
 <Typography.Paragraph type="secondary">编辑时凭据留空表示保留原值。身份范围映射仅在确认采集范围一致后填写；留空时保留独立发现记录。</Typography.Paragraph>{[{name:'identity_sensor',label:'身份采集器标识'},{name:'identity_campus',label:'身份校区标识'},{name:'identity_vlan',label:'身份 VLAN 范围'},{name:'identity_vrf',label:'身份 VRF 范围'}].map(f=><Form.Item key={f.name} name={f.name} label={f.label}><Input/></Form.Item>)}<Form.Item name="interval_seconds" label="轮询间隔（秒）"><InputNumber min={60} max={86400}/></Form.Item><Form.Item name="enabled" label="启用定时采集" valuePropName="checked"><Switch/></Form.Item></Form></Modal>
 <Modal title="发现证据" open={!!detail} footer={null} onCancel={()=>setDetail(undefined)}><div className="discovery-source-list">{detail?.observations.map(o=><article className="discovery-card" key={o.id}><strong>{origins[o.origin]??o.origin}</strong><div>{o.ip} {o.mac}</div>{o.port&&<div>端口 {o.port}</div>}{o.vlan&&<div>VLAN {o.vlan}</div>}<div>读取时间 {new Date(o.observed_at).toLocaleString('zh-CN',{hour12:false})}</div><div>{o.explanation}</div><Typography.Text type="secondary">事件 {o.id}</Typography.Text></article>)}</div></Modal></main>
}
