import { ApprovalPreview } from '../features/policies/ApprovalPreview'
import { ProxyProtocolView } from '../entities/evidence/ProxyProtocolView'
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, Button, Card, Empty, Form, Input, InputNumber, Modal, Select, Switch, Tag, Typography, message } from 'antd'
import { policiesAPI, type Policy, type Simulation } from '../features/policies/api'
import { useSession } from '../shared/api/queries'
import { can } from '../shared/auth/permissions'
import { AppPageHeader, AppLoadingState, AppErrorAlert } from '../shared/ui'

const triggerNames: Record<string,string> = {quota_exceeded:'设备配额',shared_access:'共享上网风险',explicit_proxy:'明确代理风险'}
const modeNames: Record<string,string> = {observe:'仅观测',manual:'人工确认',automatic:'自动执行'}
const reasonNames: Record<string,string> = {shared_session_generation_missing:'缺少认证会话代次',shared_session_generation_changed_within_window:'观测期间认证会话发生变化',shared_features_lack_repeated_coexistence:'共享特征缺少重复采样或时间共现',invalid_shared_evidence:'共享证据格式无效',stale_or_invalid_shared_window:'观测已过期或时间窗口无效',shared_observation_conflict:'观测记录存在冲突',invalid_shared_ip:'观测 IP 无效',missing_access_scope:'缺少园区或接入域',unregistered_shared_source:'采集来源未登记',ambiguous_shared_source_scope:'采集来源范围冲突',shared_source_scope_mismatch:'观测范围与来源配置不一致',shared_identity_unknown_or_conflicting:'事件时身份未知或冲突',shared_identity_changed_within_window:'观测期间账号发生变化',incomplete_shared_observation_window:'观测窗口不完整',shared_device_identity_insufficient:'缺少可确认的设备身份',insufficient_independent_shared_signals:'独立共享信号不足',missing_shared_scope_observation:'该接入位置缺少观测',shared_scope_account_changed:'该接入位置的账号已变化',shared_evidence_unavailable:'共享证据暂不可用',shared_access_observation_only:'共享证据当前仅用于观测',shared_evidence_insufficient_or_expired:'共享证据不足或已过期',no_shared_basis_in_complete_window:'当前完整窗口未发现共享依据',corroborated_shared_access_basis_requires_review:'存在共享依据，仍需核对组织策略',proxy_evidence_unavailable:"代理证据暂不可用",no_fresh_confirmed_proxy_evidence:"没有可归责的有效成功连接证据",confirmed_proxy_connection_requires_review:"检测到成功代理连接，需人工复核是否违规",proxy_automatic_forbidden:"此类证据禁止自动处置",proxy_evidence_changed_review_again:"证据发生变化，请重新复核",disabled:'策略未启用',selected:'按优先级选中',scope_or_schedule_mismatch:'范围或时段不匹配',exempt:'命中豁免',higher_priority_policy_selected:'同类触发已选中更高优先级策略',risk_evidence_not_evaluated:'风险证据评估尚未接入',identity_or_device_coverage_incomplete:'身份或设备覆盖不足',no_fresh_online_inventory:'无新鲜在线清单',total_exceeded:'总设备数超限',mobile_exceeded:'手机数超限',pc_exceeded:'电脑数超限'}
const emptyPolicy = (): Policy => ({policy_id:'',name:'',enabled:false,priority:0,mode:'observe',trigger:'quota_exceeded',scope:{},exempt:{},limits:{total:null,mobile:null,pc:null},sustain_seconds:0,window_seconds:86400,recovery_seconds:0,cooldown_seconds:0,stages:[]})
export function PoliciesPage(){
 const query = useQuery({queryKey:['policies'],queryFn:policiesAPI.list})
 const executions = useQuery({queryKey:['policy-executions'],queryFn:policiesAPI.executions})
 const cache = useQueryClient(); const session = useSession()
 const writable=can(session.data,'policies:manage')
 const [approvalId,setApprovalId]=useState<string>();
 const [editing,setEditing]=useState<Policy|null>(null);const [creating,setCreating]=useState(false)
 const [form]=Form.useForm<Policy>();const trigger=Form.useWatch("trigger",form);const [account,setAccount]=useState('');const [simulation,setSimulation]=useState<Simulation|null>(null)
 const save=useMutation({mutationFn:(p:Policy)=>policiesAPI.save(p,creating),onSuccess:()=>{setEditing(null);void cache.invalidateQueries({queryKey:['policies']});message.success('策略已保存')},onError:(e:Error)=>message.error(e.message)})
 const simulate=useMutation({mutationFn:(id:string)=>policiesAPI.simulate(id,account),onSuccess:setSimulation,onError:(e:Error)=>message.error(e.message)})
 const operation=useMutation({mutationFn:({id,op}:{id:string;op:'approve'|'revoke'})=>policiesAPI.operation(id,op),onSuccess:()=>{void cache.invalidateQueries({queryKey:['policy-executions']})},onError:(e:Error)=>message.error(e.message)})
 if(query.isLoading)return <AppLoadingState rows={5}/>
 if(query.isError)return <AppErrorAlert title="策略加载失败"/>
 const edit=(p:Policy,isNew=false)=>{setCreating(isNew);setEditing(p);form.setFieldsValue(p)}
 return <div className="policies-page">
 <AppPageHeader title="防代理策略" subtitle="设备配额、共享上网和明确代理分别评估，处置范围为账号全部在线会话。"/>
 <div className="policy-toolbar"><Input aria-label="试算账号" placeholder="输入认证账号进行试算" value={account} onChange={e=>setAccount(e.target.value)}/><Button type="primary" disabled={!writable} onClick={()=>edit(emptyPolicy(),true)}>新建策略</Button></div>
 <Alert type="info" showIcon title="新建策略默认禁用、仅观测" description="配额只统计可独立区分的已确认终端。身份覆盖不足时保留不确定；超配额不等于代理。"/>
 <div className="policy-cards">{query.data?.items.map(p=><Card key={p.policy_id} title={p.name}>
 <div className="policy-tags"><Tag>{triggerNames[p.trigger]}</Tag><Tag>{modeNames[p.mode]}</Tag><Tag>{p.enabled?'已启用':'未启用'}</Tag></div>
 <Typography.Paragraph>优先级 {p.priority} · 持续 {p.sustain_seconds} 秒 · {p.stages.length} 个动作阶段</Typography.Paragraph>
 <Typography.Paragraph>设备上限：总数 {p.limits.total??'不限'} / 手机 {p.limits.mobile??'不限'} / 电脑 {p.limits.pc??'不限'}</Typography.Paragraph>
 <Typography.Text type="secondary" className="policy-identifier">{p.policy_id}</Typography.Text>
 <div className="policy-toolbar"><Button disabled={!writable} onClick={()=>edit(p)}>编辑策略</Button><Button disabled={!account.trim()} loading={simulate.isPending} onClick={()=>simulate.mutate(p.policy_id)}>策略试算</Button></div>
 </Card>)}</div>{!query.data?.items.length&&<Empty description="尚未配置防代理策略"/>}
 {simulation&&<Card title={`账号 ${simulation.account_id} 的试算结果`}>
 <Typography.Paragraph>已确认终端 {simulation.inventory.total} 台 · 手机 {simulation.inventory.mobile} · 电脑 {simulation.inventory.pc} · 其他 {simulation.inventory.other} · 不确定会话 {simulation.inventory.uncertain_sessions}</Typography.Paragraph>
 {!simulation.inventory.coverage_complete&&<Alert type="warning" title="覆盖不足，无法完整判断在线设备数"/>}
 {simulation.explanations.map(e=><p key={e.policy_id} className="policy-identifier">{e.policy_id}：{reasonNames[e.reason]??e.reason}</p>)}
 {simulation.evaluations.map(e=><div key={e.policy_id}><p>{e.shared_evaluation ? (e.input.known ? (e.input.violated ? '存在共享依据' : '当前未命中') : '证据不足') : e.input.known?(e.input.violated?'违规成立':'未超限'):'无法判断'}：{e.input.reasons.map(r=>reasonNames[r]??r).join('、')}</p>{e.proxy_evidence?.map(proof=><ProxyProtocolView key={proof.evidence_id} evidence={proof}/>)}{e.shared_error&&<Alert type="warning" title="共享证据读取失败" description="本次保留证据不足，不作为恢复依据。"/>}{e.shared_evaluation?.map((proof,index)=><div className="policy-execution policy-identifier" key={proof.id??`${proof.ip}-${proof.sensor_id}-${index}`}><strong>{proof.ip} · {{basis_present:'存在共享依据',not_matched:'当前未命中',insufficient:'证据不足'}[proof.state]}</strong><p>事件时账号：{proof.account_id||'未知'} · 园区：{proof.campus_id||'未知'} · 接入域：{proof.access_domain||'未知'}</p><p>已确认设备下界：{proof.quantity_known?proof.device_lower_bound:'不可确定'} · 传感器：{proof.sensor_id||'未登记'}</p><p>观测窗口：{proof.from||'未知'} — {proof.to||'未知'}</p><p>信号：{proof.signal_groups?.map(group=>({ua_os:'UA 系统差异',ttl_path:'TTL 路径差异',tls_stack:'TLS 特征差异',dhcp_stack:'DHCP 特征差异',confirmed_same_exit_endpoints:'同出口已确认终端'}[group]??group)).join('、')||'不足'}</p><p>规则：{proof.rule_version||'不可用'} · 来源配置：{proof.config_version||'不可用'}</p><p>{proof.reasons.map(reason=>reasonNames[reason]??reason).join('、')}</p><details><summary>原始记录依据</summary>{proof.records?.length?proof.records.map(record=><p key={`${record.source}-${record.collector_instance_id}-${record.event_id}`}>{record.source} · {record.collector_instance_id||'实例未知'} · {record.event_id}</p>):<p>暂无可用原始记录引用</p>}</details></div>)}</div>)}
 </Card>}
 <Modal title="确认策略执行" open={Boolean(approvalId)} footer={null} destroyOnHidden onCancel={()=>setApprovalId(undefined)}>{approvalId&&<ApprovalPreview key={approvalId} id={approvalId} onComplete={()=>{setApprovalId(undefined);void cache.invalidateQueries({queryKey:['policy-executions']})}}/>}</Modal>
 <Card title="策略执行记录">{executions.isError?<AppErrorAlert title="执行记录加载失败"/>:executions.data?.items.length?executions.data.items.map(e=><div className="policy-execution" key={e.execution_id}><strong className="policy-identifier">{e.account_id} · {e.policy_id}</strong><p>第 {e.episode} 轮 · {e.state}</p><p>{e.reasons.map(r=>reasonNames[r]??r).join('、')}</p>{e.proxy_evidence?.map(proof=><ProxyProtocolView key={proof.evidence_id} evidence={proof}/>)}{e.stages.map(st=><p key={st.index}>阶段 {st.index+1}：{st.status} · {st.action_ids.length} 个子动作</p>)}<div className="policy-toolbar"><Button disabled={!can(session.data,'policies:authorize')||!e.stages.some(st=>st.status==='awaiting_approval')} onClick={()=>setApprovalId(e.execution_id)}>确认执行</Button><Button disabled={!can(session.data,'actions:revoke')} onClick={()=>operation.mutate({id:e.execution_id,op:'revoke'})}>撤销本轮</Button></div></div>):<Empty description="暂无执行记录"/>}</Card>
 <Modal className="policy-modal" title={creating?'新建防代理策略':'编辑防代理策略'} open={!!editing} onCancel={()=>setEditing(null)} onOk={()=>form.submit()} confirmLoading={save.isPending} width={800}>
 <Form form={form} onValuesChange={(changed,values)=>{if((changed.trigger==='explicit_proxy'&&values.mode==='automatic')||(changed.trigger==='shared_access'&&values.mode==='automatic'))form.setFieldValue('mode','observe')}} layout="vertical" onFinish={values=>save.mutate({...editing!,...values})}>
 <Form.Item name="policy_id" label="策略 ID" hidden><Input/></Form.Item>
 <Form.Item name="name" label="策略名称" rules={[{required:true}]}><Input/></Form.Item>
 <div className="policy-form-grid"><Form.Item name="enabled" label="启用" valuePropName="checked"><Switch disabled={creating}/></Form.Item><Form.Item name="mode" label="处置模式"><Select disabled={creating} options={Object.entries(modeNames).map(([value,label])=>({value,label,disabled:(trigger==='explicit_proxy'&&value==='automatic')||(trigger==='shared_access'&&value==='automatic')}))}/></Form.Item><Form.Item name="trigger" label="触发类型"><Select options={Object.entries(triggerNames).map(([value,label])=>({value,label}))}/></Form.Item><Form.Item name="priority" label="优先级"><InputNumber/></Form.Item></div>
 <Typography.Title level={5}>适用范围</Typography.Title>
 <div className="policy-form-grid">{(['accounts','groups','products','campuses','vlans','cidrs'] as const).map((key,i)=><Form.Item key={key} name={['scope',key]} label={['账号','用户组','产品','园区','VLAN','IP 范围（CIDR）'][i]}><Select mode="tags" tokenSeparators={[',']} open={false}/></Form.Item>)}</div>
 <Form.Item name={['scope','weekdays']} label="生效星期（北京时间，留空为每天）"><Select mode="multiple" options={['日','一','二','三','四','五','六'].map((day,value)=>({value,label:`星期${day}`}))}/></Form.Item>
 <div className="policy-form-grid"><Form.Item name={['scope','start_minute']} label="开始时间（当天第几分钟）"><InputNumber min={0} max={1439} placeholder="留空为全天"/></Form.Item><Form.Item name={['scope','end_minute']} label="结束时间（当天第几分钟）"><InputNumber min={0} max={1439} placeholder="与开始时间一起填写"/></Form.Item></div>
 <Typography.Title level={5}>豁免范围</Typography.Title><div className="policy-form-grid">{(['accounts','groups','products','campuses','vlans','cidrs'] as const).map((key,i)=><Form.Item key={key} name={['exempt',key]} label={['账号','用户组','产品','园区','VLAN','IP 范围（CIDR）'][i]}><Select mode="tags" tokenSeparators={[',']} open={false}/></Form.Item>)}</div>
 <div className="policy-form-grid">{(['total','mobile','pc'] as const).map((key,i)=><Form.Item key={key} name={['limits',key]} label={['总设备上限','手机上限','电脑上限'][i]}><InputNumber min={0} placeholder="不限制"/></Form.Item>)}</div>
 <div className="policy-form-grid">{(['sustain_seconds','window_seconds','recovery_seconds','cooldown_seconds'] as const).map((key,i)=><Form.Item key={key} name={key} label={['持续秒数','复发统计窗口秒数','恢复持续秒数','冷却秒数'][i]}><InputNumber min={0}/></Form.Item>)}</div>
 <Typography.Title level={5}>动作阶段</Typography.Title>
 <Form.List name="stages">{(fields,{add,remove})=><>{fields.map(field=><div className="policy-stage" key={field.key}><div className="policy-form-grid"><Form.Item name={[field.name,'action']} label="动作" rules={[{required:true}]}><Select options={(trigger==='shared_access'?[{value:'disconnect',label:'强制下线'}]:[{value:'notify',label:'通知'},{value:'rate_limit',label:'限速'},{value:'disconnect',label:'强制下线'},{value:'disable_account',label:'停用账号'}])}/></Form.Item><Form.Item name={[field.name,'connector_id']} label="控制器 ID" rules={[{required:true}]}><Input/></Form.Item>{(['after_seconds','min_episodes','duration_seconds','rate_kbps'] as const).map((key,i)=><Form.Item key={key} name={[field.name,key]} label={['前置等待秒数','最少违规轮次','有效秒数','限速 Kbps'][i]}><InputNumber min={0}/></Form.Item>)}</div><Form.Item name={[field.name,'template']} label="通知模板"><Input.TextArea rows={2}/></Form.Item><Button onClick={()=>remove(field.name)}>删除阶段</Button></div>)}<Button onClick={()=>add({action:trigger==='shared_access'?'disconnect':'notify',connector_id:'',after_seconds:0,min_episodes:1,duration_seconds:0,rate_kbps:0,template:''})}>添加动作阶段</Button></>}</Form.List>
 </Form></Modal>
 </div>
}
